[package]
name = "extract_sprites"
version = "0.1.0"
authors = ["Simon Frankau <sgf@arbitrary.name>"]
edition = "2018"

[dependencies]
# Old version that doesn't depend on a version of nanorand that depends on edition2021.
image = "0.23.14"
anyhow = "1.*"
