[package]
name = "find_palettes"
version = "0.1.0"
authors = ["Simon Frankau <sgf@arbitrary.name>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
